### PR TITLE
add in-place (with attributes) configuration

### PR DESCRIPTION
**Pull request by khoden**
update docs
update min
add lazy load api.js

### CODE REVIEW

**Comment by khoden** [comment]
very fast)

**Comment by khoden** [comment]
perhaps, need to increment version

**Comment by emorvillez** [comment]
Done !
but I fix a bug with callback to update model: _p.callback was updated but code used params variable in the render method so nothing happened. I fix that quickly so if you want to check ;) thanks for you contribution

**Comment by khoden** [comment]
thx

**Pull request merged**
